scaleapi/scaleapi-python-client

scaleapi/__init__.py, tests/test_client.py
and also mark the `task/phonecall` endpoint tests for pytest to skip for now, since tox was failing and I saw the message on the support Slack regarding that one's deprecation.
If I'm being too forward with the latter change, I can limit my PR to just the former change.
=> Add 'phrases' to ALLOWED_FIELDS for audio transcription task, fix tests

setup.py
enum34 is a package that backports python 3.4 enum functionality to earlier
versions. However, it only includes the functionality as of 3.4. If other
packages use more recent enum functionality, this will break them. (See #17
for more details.)
The solution is just to install enum34 only when the python version is
pre-3.4.
Fixes #17
=> Only install enum34 on python before 3.4

.circleci/config.yml, README.rst, docs/dev_requirements.txt, docs/developer_guide.md, publish.sh, scaleapi/_version.py, scaleapi/api.py, tests/test_client.py
- Readme Updates
- CircleCI Configuration
- Added [500] error code to HTTP Retry cases
=> [v2.0.1] CircleCI, 500 Error code, Readme updates

scaleapi/tasks.py
`fetch_task` is deprecated, and replaced with `get_task`
=> replaced fetch_task with get_task

README.rst, scaleapi/_version.py, scaleapi/api.py, scaleapi/exceptions.py
SDK now recognizes the `503` Response Code and applies retry since it's a timeout kind of error, driven by the backend.
=> Handling 503 Response Code

.circleci/config.yml, scaleapi/_version.py, scaleapi/api.py, scaleapi/exceptions.py
- Extended retry list with Cloudflare exception codes
- Small improvements on default Exception handling
=> [v2.0.4] Extended exceptions for Cloudflare error codes

scaleapi/__init__.py
Adds arg self_serve to project creation function
Support for this has now been added to the Scale's project creation API and the docs are updated https://docs.scale.com/reference#project-creation
=> Add self_serve arg to project creation.

README.rst, tests/test_client.py
- Updated Readme file to include `conda-forge` installation command: `conda install -c conda-forge scaleapi`
- Updated Readme to have more examples for task.as_dict() and Files API
- Update/fix test cases with batch status
=> Update Readme and tests

scaleapi/__init__.py, scaleapi/api.py
The Python client only works with Scale's public API. This enables it to be used with separate API instances.
```
sc = ScaleClient(MY_API_KEY, api_instance_url="https://separate.api.env.scale.com/v1")
```
=> Enable client to operate against different API instances

README.rst, docs/migration_guide.md, docs/pypi_update_guide.md, docs/release_notes_template.md, scaleapi/__init__.py, scaleapi/_version.py, scaleapi/exceptions.py, tests/test_client.py
- Implemented `get_tasks_count()` to return number of tasks for given parameters
- Renamed `ScaleDuplicateTask` to `ScaleDuplicateResource` as it's used for batches and projects
- Documentation updates:
- Readme with new examples and notes
- Deployment guide refers to CircleCI flow
- `Release Notes Template` added in order to standardize the published notes.
=> Version 2.2.0 changes

scaleapi/__init__.py, scaleapi/_version.py
Add support for self_label_batch creation on Rapid.
=> [2.4.0] Add support for rapid self_label_batch creation

README.rst, scaleapi/__init__.py, scaleapi/training_tasks.py
Add endpoints that were added here: https://github.com/scaleapi/scaleapi/pull/37333
=> Add training tasks endpoint to Python client

.pylintrc, README.rst, scaleapi/__init__.py, scaleapi/_version.py, scaleapi/evaluation_tasks.py, scaleapi/quality_tasks.py, scaleapi/training_tasks.py
bump version to 2.8 following changes
=> Version change

README.rst, scaleapi/__init__.py, scaleapi/_version.py, scaleapi/api.py, scaleapi/tasks.py, tests/test_client.py
- Updated cancel_task and task.cancel() method with clear_unique_id option
- Implemented delete_request (yay! for the first time in our API) and added DELETE to retry list
- Implemented update_task_unique_id at API level and task.update_unique_id at task level
- Implemented clear_task_unique_id at API level task.clear_unique_id as task level
- Added two new test cases for test_update_unique_id and test_clear_unique_id
- Updated README with new examples related to updates above ^
=> Update cancel_task to add clearUniqueId option

README.rst, examples/cancel_batch.py
Ref: 
See https://scaleapi.slack.com/archives/C02150T5FB9/p1652137855727189?thread_ts=1652135470.004439&cid=C02150T5FB9
Related: https://github.com/scaleapi/sail/pull/9
=> Example Scripts Folder

scaleapi/api.py
Here's the test on Python that's run with Pytest:
Here's the console.logs from the local-machine where I'm "reproducing" a similar error (returns 500, but successfully creates task):
So, the test for this was kinda weird, I made our task creation handler force an error during the first task creation. This had to be forced after the task has been created, but before the 200 is sent back. 
The same error can't happen on the second task creation, but it should fail in a 409
=> False 500 testing

scaleapi/_version.py
Bumping version for incremental release
Draft Release here: https://github.com/scaleapi/scaleapi-python-client/releases/edit/untagged-d5d4cd9c3d7b2339c10e
Referencing this pr: https://github.com/scaleapi/scaleapi-python-client/pull/57
=> bumping incremental version

.github/pull_request_template.md
Adding a PR template for the repo to ensure developers follow certain guidance (testing, documentation) and to remind them to review the deployment guide and include version increments if needed in their PRs.
=> Introduce a PR template to the repo

README.rst, scaleapi/__init__.py, scaleapi/_version.py, scaleapi/api.py, scaleapi/tasks.py
- Implementing existing task accept/reject API for audits to SDK
- `client.audit_task()` as well as `task.audit()` are implemented methods
- Readme is updated with examples
`TODO:` Testing of audit endpoint via test task/project is not available so that part is to-be implemented later.
Implementing already existing audit API endpoint into the SDK.
https://docs.scale.com/reference/audit-a-task
=> Add task audit endpoints to SDK

.gitignore, .pylintrc, README.rst, scaleapi/__init__.py, scaleapi/_version.py, scaleapi/api.py, scaleapi/studio.py, scaleapi/teams.py, tests/t_studio.py, tests/test_client.py
Studio API endpoints
TODO BEFORE MERGE:
included a t_studio.py file since Studio endpoints require live projects
=> studio-api

README.rst, scaleapi/__init__.py, scaleapi/_version.py, scaleapi/api.py, scaleapi/tasks.py, tests/test_client.py
_Please include a summary of the changes. Please also include the relevant context and motivation. List any dependencies and assumptions that are required for this change._
Implemented task tags endpoints to set, add, and delete tags from a given task.
=> Implemented Task Tags Endpoints

README.rst
The sample line `print(f"{len(task_list))} tasks retrieved")` has an extra `)` in it. Let's fix that.
=> Fix minor typo in get_tasks code sample

.gitignore, scaleapi/__init__.py
- Allows project creation to be linked to an existing dataset
[[sc-747086]](https://app.shortcut.com/scaleai/story/747086)
=> allow datasetId on project creation

README.rst, scaleapi/__init__.py, scaleapi/_version.py, scaleapi/api.py
- Adding proxy support to SDK Client initialization. Now users can pass `proxies`, `cert` and `verify` parameters to their `requests`
```py
proxies = { 'https': 'http://10.10.1.10:1080' }
client = scaleapi.ScaleClient(
api_key="YOUR_API_KEY_HERE",
proxies=proxies,
cert='/path/client.cert',
verify=True
)
```
_Please include a summary of the changes. Please also include the relevant context and motivation. List any dependencies and assumptions that are required for this change._
=> adding proxy support to SDK

.pre-commit-config.yaml, scaleapi/__init__.py, scaleapi/_version.py
Added an `exclude_archived` additional filter to remove archived batches on retrieval.
=> exclude_archived param added to batches retrieval 

README.rst, scaleapi/_version.py
added exclude_archive to readme and version bump
=> Readme and version bump

scaleapi/_version.py, scaleapi/api.py
This pull request introduces several improvements and enhancements to the existing Python script. The key changes are outlined below:
- In the `Api` class constructor (`__init__` method), we now validate the provided API key to ensure it is not empty or `None`. If the key is invalid, a `ScaleException` is raised with the message "Please provide a valid API Key."
- The error handling logic has been improved in the `_api_request` method. Specifically, when encountering a 409 HTTP status code and specific conditions are met (endpoint contains "task" and `body` contains a "unique_id"), the code checks for retry history and performs additional API requests to retrieve task data if necessary.
- The code has been refactored to enhance readability and maintainability. Descriptive variable names …
=> Error Handling Enhancements

README.rst, scaleapi/__init__.py, scaleapi/_version.py
Added the limited_response argument to the get_tasks() method
=> v2.15.1 Adding limit_response to get_tasks method

scaleapi/__init__.py, scaleapi/_version.py, scaleapi/batches.py, scaleapi/projects.py, tests/test_client.py
adds support for TaskBatch metadata, set TaskBatch Metadata, and project taxonomy templates.
adds support for TaskBatch metadata, set TaskBatch Metadata, and project taxonomy templates.
=> add task batch metadata and task templates support

scaleapi/_version.py, scaleapi/projects.py
fixes small bug causing template_fetching to crash since project is no longer returned in the schema
=> remove project from template schema

scaleapi/_version.py, scaleapi/tasks.py, tests/test_client.py
Add support for the ChatExperimental task type. I am also adding the endpoint in the main repo. 
=> Add ChatExperimental TaskType

README.rst, scaleapi/__init__.py, scaleapi/_version.py, tests/test_client.py
Adding `limit` option to `get_tasks` method to allow selecting a certain limit for every pull from API. 
Limit is propagated to `/tasks` endpoint.
=> Adding limit option to get_tasks method

scaleapi/_version.py, scaleapi/api.py
This change handles elegantly in case a Session object doesn't have retries and retry history objects.
=> Handle non-existing retries within Session object

scaleapi/api.py
Handle potentially missing `raw` and `retries` attributes of Response elegantly, in case they're not populated by the underlying request/urllib3 objects.
=> Handle missing raw and retries on Response

scaleapi/__init__.py, scaleapi/_version.py, tests/test_client.py
**Optional `project_name` Parameter for `get_tasks()` Function in Python SDK**
**Description:**
This release includes an important update to the Scale API Python SDK that makes the `project_name` parameter optional for the `get_tasks()` function. Previously, `project_name` was a required parameter, which limited the flexibility of querying tasks. 
**Usage:**
- When calling `get_tasks()`, you can now omit the `project_name` parameter:
```python
tasks = scale_client.get_tasks(batch_name='example_batch', status='TaskStatus.Completed')
```
- The function will work correctly with just the `batch_name` and `status` parameters, enhancing flexibility and ease of use.
**Additional Notes:**
- This change is backward-compatible; existing code with the `project_name` parameter will continue to …
=> Make project name optional

scaleapi/__init__.py, scaleapi/_version.py, tests/test_client.py
`project_name` will be optional for `get_tasks_count` method. 
Providing either project or batch name will be enough to be consumed with the method.
=> Make project_name optional for get_tasks_count

scaleapi/_version.py, scaleapi/projects.py
adds response_schema and auto_onboard_enabled as properties to project-template class
adds helper methods to get response_schema and auto_onboard_enabled values
bumps version up
adds response_schema and auto_onboard_enabled as properties to project-template class
adds helper methods to get response_schema and auto_onboard_enabled values
tested locally since feature is gated behind feature-flag
=> add auto-onboard functionality to sdk

README.rst
_Please include a summary of the changes. Please also include the relevant context and motivation. List any dependencies and assumptions that are required for this change._
=> Update readme with the new documentation links

.circleci/config.yml, publish.sh
Fix publish twine version. Currently gives this error when publishing: `InvalidDistribution: Invalid distribution metadata: unrecognized or malformed field 'license-file'`
=> Fix publish twine version
